### PR TITLE
Enable multiple bindings for developer name

### PR DESCRIPTION
**Pull request by osieckiAdam**
The goal of this PR is to make possible to have multiple bindings for the same class, details could be found in discussion here: https://github.com/apex-enterprise-patterns/force-di/issues/81 CC: @ImJohnMDaniel 

---
This change is [Reviewable](https://reviewable.io/reviews/apex-enterprise-patterns/force-di/82)

### CODE REVIEW

**Comment by ImJohnMDaniel** [comment]
@osieckiAdam, thanks for opening the PR.  At first glance, this is an interesting idea.  If you don't mind, please give me and my colleagues some time to mull these changes over.  

One quick question would be, have you tested these changes when the platform cache option is activated?

**Comment by osieckiAdam** [comment]
@ImJohnMDaniel I wouldn't say that I performed some big tests, but yes I activated the platform cache and confirmed that it still works fine, I also modified my records (changed the sequence, added new binding metadata) and it still worked. However, I have some thoughts and doubts about the caching code 
1) Inline help text for field OrgCachePartitionName__c seems to be not correct. It says "The partition name to store the binding records to.  If this value is not specified, the bindings will be stored to the main Org Platform Cache." but I have an impression that this is not true - see the method isStoringBindingInPlatformCache - it checks if getPartition is null, when partition name is empty then getPartition is returning null

2) di_PlatformCache.getInstance().retrieveBinding method is returning results only for bindings with bindingSObjectType != null, so it looks like for my use case platform cache will not be used, is this expected behavior ? Does it mean that binding is working only for records with bindingSObjetType?

**Review by ImJohnMDaniel — APPROVED** [review]

**Review by stohn777 — COMMENTED** [review]
I submitted to comments with my review.  Only the refactoring of the ToString method is blocking.

> *[Reviewable](https://reviewable.io/reviews/apex-enterprise-patterns/force-di/82#-:-MvjJVVg0qI8igizGBQt:bo2z02f)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @osieckiAdam)

**Comment by ImJohnMDaniel** [comment]
@osieckiAdam -- Just checking in on the progress related to @stohn777's [request for changes](https://github.com/apex-enterprise-patterns/force-di/pull/82#pullrequestreview-880882585).  If you can let us know when you have a moment, that would be great.  Cheers!

**Comment by osieckiAdam** [comment]
@ImJohnMDaniel sorry for the delay, it's been a crazy week for me
@stohn777 thanks for review, let me answer to your comments:
1) refactor of toString method - good catch, see the latest commit, I did it as you recommended
2) whitespace changes - it looks that some auto-formatting from John's merge commit added this one https://github.com/apex-enterprise-patterns/force-di/pull/82/commits/90957af34d644a41582e87b99b082880959d4501  I reverted them in my commit

**Review by stohn777 — COMMENTED** [review]
@osieckiadam 
Thanks for the submission and follow-up!!

> *[Reviewable](https://reviewable.io/reviews/apex-enterprise-patterns/force-di/82#-:-MwT9xHl1IGD9IhQW9tv:b-2xb8eg)* status: 0 of 9 files reviewed, all discussions resolved (waiting on @osieckiAdam)

**Review by stohn777 — APPROVED** [review]
> Reviewed 7 of 9 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/apex-enterprise-patterns/force-di/82)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osieckiAdam)

**Review by ImJohnMDaniel — APPROVED** [review]

**Comment by ImJohnMDaniel** [comment]
@osieckiAdam Thanks for the submission

**Comment by fransf-wtax** [comment]
Hi @osieckiAdam @ImJohnMDaniel . Does this change also add the ability to inject *all* bindings for a particular type? Similar to Spring Framework's behavior when auto-wiring a list of a type: it injects a list containing all beans of that type.

Would be very useful for implementing e.g. an observer pattern where you want to be able to bind one or more observers (implementing an interface) that are dependency-injected into the observable (calling the observer interface). Thanks!

If it's not a current feature, it seems like something that would be easy to add based on the changes in this PR? Do you agree, or do you see potential issues? I'd imagine adding `getInstances` methods to `di_Injector` that return a `List` of the type you requested, ordered by the binding sequence.

Would appreciate your thoughts!

**Comment by osieckiAdam** [comment]
@fransf-wtax Yeah, to me it makes sense,
If I understand you correctly, you want to achieve something similiar to ApexTypeImplementor but controlled by metadata and also having an order, right?

**Comment by fransf-wtax** [comment]
@osieckiAdam I guess you could phrase it that way.

Currently the `getInstance` methods assume there's just one bindings and return the first if there are multiple:
```
    public Object getInstance(String developerName, Object params) {
        if ( String.isBlank(developerName) ) {
            throw new InjectorException('Request for Binding cannot take "developerName" parameter of null');
        }
        List<di_Binding> bindingsFound = this.Bindings.byName( developerName.toLowerCase().trim() ).get();
        if ( bindingsFound == null || bindingsFound.isEmpty() ) {
            throw new InjectorException('Binding for "' + developerName + '" not found');
        }
        return bindingsFound[0].getInstance(params);
    }
```
See how it does `bindingsFound[0]`. I'm actually interested in *all* the bindings found.

I would basically be proposing to add `getInstances` (plural) methods that return `List<Object>` instead of `Object`.

I still don't understand what the versions of `getInstance` that take a `Schema.SObjectType bindingSObjectType` parameter are for, so I don't know if it would make sense to do it for them as well. It might make it more consistent.

**Pull request merged**
