### PR TITLE
Improve test coverage

### PR DESCRIPTION
**Pull request by fransf-wtax**
I wasn't able to deploy this project in my org because some classes had less than the required 75% coverage. I added / amended some unit tests to achieve at least 75% coverage on all Apex classes.

- - -
This change is [Reviewable](https://reviewable.io/reviews/apex-enterprise-patterns/force-di/89)

### CODE REVIEW

**Review by ImJohnMDaniel — CHANGES_REQUESTED** [review]
@fransf-wtax -- while I appreciate the attempt here, we won't be able to add cache partitions to the code base because not all orgs either use cache or already have partitions established.

For the moment, I am going to vote no on this PR but I will think about the potential for how we could make something like this work.

**Comment by ImJohnMDaniel** [comment]
@fransf-wtax, I am assuming that you were trying to deploy this not as a full unit but rather as individual elements.  I know that the repo's total code coverage is more than sufficient for production org deployment.  If my assumption is incorrect, please me know.

**Comment by fransf-wtax** [comment]
@ImJohnMDaniel Thanks for your feedback. 

I deployed the whole project but specified test level as `RunSpecifiedTests` because I don't want to run my entire org's tests (which takes hours). However, this sets the minimum test coverage _for each class_ to 75% as described on https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_deploy_run_specific_tests.htm . Hence the need to increase test coverage for each class where it was below 75%, even if the total test coverage for all classes combined was over 75%.

There might be more people wanting to deploy the project this way, so while I totally understand your considerations about creating cache partitions, I can imagine the PR has value for some people.

I'll just keep it on my own fork for now so we can use it within our organisation. I'll leave it up to you what to do with it from here on :-)

**Comment by ImJohnMDaniel** [comment]
@fransf-wtax -- understood.  If you would like to maintain your fork for others, that would be appreciated.  Having said that, I will close this PR then.

**Pull request closed without merging**
