### PR TITLE
Add field to binding obj to filter active records

### PR DESCRIPTION
**Pull request by aronowt**
This change is [Reviewable](https://reviewable.io/reviews/apex-enterprise-patterns/force-di/62)

### CODE REVIEW

**Comment by afawcett** [comment]
@aronowt for backwards compatibility this change needs to consider null values in Active__c as active. cc @ImJohnMDaniel thoughts?

**Comment by ImJohnMDaniel** [comment]
@aranowt -- While the change is certainly straightforward and I echo @afawcett's requested changes, my larger question is why would you need to do this?  Why would you have bindings deployed that are not active?

**Comment by aronowt** [comment]
We have two uses for it at the moment.

1) Deploy items as soon as the development is completed and activate it
only when it's supposed to go live. It would be easier to find what to
activate if the binding is there but deactivated, as opposed to not being
there at all.
2) Deactivate certain processes when doing a data load.

**Comment by ImJohnMDaniel** [comment]
@aronowt If a binding is not active and a process calls for that binding, there would be an error.  If you are using the bindings as "feature switches", then this may not be the best way to do that.  The purpose of the bindings provide a way for you change implementations and limit what needs to be deployed as part of that change.  It also supports unit test mock swap-out of implementations.  

Am I understanding your use case correctly or am I missing something?

**Comment by ImJohnMDaniel** [comment]
Closing due to inactivity.

**Pull request closed without merging**
